/datum/voicepack/male/foppish/get_sound(soundin, modifiers)
	var/used
	switch(soundin)
		if("gasp")
			used = list('sound/vo/male/foppish/gasp (1).ogg', 'sound/vo/male/foppish/gasp (2).ogg', 'sound/vo/male/foppish/gasp (3).ogg', 'sound/vo/male/foppish/gasp (4).ogg')
		if("paincrit")
			used = list('sound/vo/male/young/paincrit (1).ogg','sound/vo/male/young/paincrit (2).ogg','sound/vo/male/young/paincrit (3).ogg')
		if("cry")
			used = list('sound/vo/male/foppish/cry (1).ogg', 'sound/vo/male/foppish/cry (2).ogg', 'sound/vo/male/foppish/cry (3).ogg')
		if("yawn")
			used = list('sound/vo/male/foppish/yawn (1).ogg', 'sound/vo/male/foppish/yawn (2).ogg', 'sound/vo/male/foppish/yawn (3).ogg')
		if("painscream")
			used = list('sound/vo/male/foppish/painscream (1).ogg', 'sound/vo/male/foppish/painscream (2).ogg', 'sound/vo/male/foppish/painscream (3).ogg', 'sound/vo/male/foppish/painscream (4).ogg')
		if("painmoan")
			used = list('sound/vo/male/foppish/painmoan (1).ogg', 'sound/vo/male/foppish/painmoan (2).ogg', 'sound/vo/male/foppish/painmoan (3).ogg', 'sound/vo/male/foppish/painmoan (4).ogg')
		if("fatigue")
			used = 'sound/vo/male/foppish/fatigue.ogg'
		if("sigh")
			used = list('sound/vo/male/foppish/sigh (1).ogg', 'sound/vo/male/foppish/sigh (2).ogg', 'sound/vo/male/foppish/sigh (3).ogg', 'sound/vo/male/foppish/sigh (4).ogg', 'sound/vo/male/foppish/sigh (5).ogg', 'sound/vo/male/foppish/sigh (6).ogg')
		if("clearthroat")
			used = list('sound/vo/male/foppish/clearthroat (1).ogg', 'sound/vo/male/foppish/clearthroat (2).ogg', 'sound/vo/male/foppish/clearthroat (3).ogg', 'sound/vo/male/foppish/clearthroat (4).ogg', 'sound/vo/male/foppish/clearthroat (5).ogg', 'sound/vo/male/foppish/clearthroat (6).ogg')
		if("sniff")
			used = 'sound/vo/male/foppish/sniff.ogg'
		if("sneeze")
			used = 'sound/vo/male/foppish/sneeze.ogg'
		if("hmm")
			used = list('sound/vo/male/foppish/hmm (1).ogg', 'sound/vo/male/foppish/hmm (2).ogg', 'sound/vo/male/foppish/hmm (3).ogg')
		if("moan")
			used = 'sound/vo/male/foppish/moan (1).ogg'
		if("snore")
			used = list('sound/vo/male/foppish/snore (1).ogg', 'sound/vo/male/foppish/snore (2).ogg', 'sound/vo/male/foppish/snore (3).ogg', 'sound/vo/male/foppish/snore (4).ogg')
		if("laugh")
			used = list('sound/vo/male/foppish/laugh (1).ogg', 'sound/vo/male/foppish/laugh (2).ogg', 'sound/vo/male/foppish/laugh (3).ogg', 'sound/vo/male/foppish/laugh (4).ogg')
		if("chuckle")
			used = list('sound/vo/male/foppish/chuckle (1).ogg', 'sound/vo/male/foppish/chuckle (2).ogg', 'sound/vo/male/foppish/chuckle (3).ogg')
		if("groan")
			used = list('sound/vo/male/foppish/groan (1).ogg', 'sound/vo/male/foppish/groan (2).ogg', 'sound/vo/male/foppish/groan (3).ogg', 'sound/vo/male/foppish/groan (4).ogg', 'sound/vo/male/foppish/groan (5).ogg', 'sound/vo/male/foppish/groan (6).ogg')
		if("pain")
			used = list('sound/vo/male/young/pain (1).ogg', 'sound/vo/male/young/pain (2).ogg', 'sound/vo/male/young/pain (3).ogg', 'sound/vo/male/young/pain (4).ogg')
		if("rage")
			used = 'sound/vo/male/foppish/rage (1).ogg'
		if("scream")
			used = list('sound/vo/male/young/firescream (1).ogg', 'sound/vo/male/young/firescream (2).ogg', 'sound/vo/male/young/firescream (3).ogg', 'sound/vo/male/foppish/scream (1).ogg', 'sound/vo/male/foppish/scream (2).ogg')
	if(!used)
		used = ..(soundin, modifiers)
	return used
