// Resident Manuscript document state keys.
#define RESIDENT_MANUSCRIPT_STATUS_COMMONER "commoner"
#define RESIDENT_MANUSCRIPT_STATUS_NOBLE "noble"

#define RESIDENT_MANUSCRIPT_VERIFICATION_NONE "none"
#define RESIDENT_MANUSCRIPT_VERIFICATION_UNKNOWN "unknown"
#define RESIDENT_MANUSCRIPT_VERIFICATION_REAL "real"
#define RESIDENT_MANUSCRIPT_VERIFICATION_FAKE "fake"

#define RESIDENT_MANUSCRIPT_SPECIAL_ITEM_NAME "Resident Manuscript"

#define RESIDENT_MANUSCRIPT_FAKE_DEFECT_CHANCE 65
#define RESIDENT_MANUSCRIPT_MIN_DEFECTS 3
#define RESIDENT_MANUSCRIPT_MAX_DEFECTS 5
