#define ITEM_CAT_ARMOR_HELMETS "Armor (Helmets)"
#define ITEM_CAT_ARMOR_CHESTPIECES "Armor (Chestpieces)"
#define ITEM_CAT_ARMOR_LEGS "Armor (Legs)"
#define ITEM_CAT_ARMOR_NECK "Armor (Neck)"
#define ITEM_CAT_ARMOR_BOOTS "Armor (Boots)"
#define ITEM_CAT_ARMOR_GLOVES "Armor (Gloves)"
#define ITEM_CAT_ARMOR_MASKS "Armor (Masks)"
#define ITEM_CAT_ARMOR_BRACERS "Armor (Bracers)"
#define ITEM_CAT_ARMOR_BELTS "Armor (Belts)"
#define ITEM_CAT_ARMOR_BARDING "Armor (Barding)"

#define ITEM_CAT_WEAPONS_SWORDS "Weapons (Swords)"
#define ITEM_CAT_WEAPONS_DAGGERS "Weapons (Daggers & Knives)"
#define ITEM_CAT_WEAPONS_AXES "Weapons (Axes)"
#define ITEM_CAT_WEAPONS_POLEARMS "Weapons (Spears & Polearms)"
#define ITEM_CAT_WEAPONS_MACES "Weapons (Maces & Hammers)"
#define ITEM_CAT_WEAPONS_FLAILS "Weapons (Flails & Whips)"
#define ITEM_CAT_WEAPONS_SHIELDS "Weapons (Shields)"
#define ITEM_CAT_WEAPONS_AMMO "Weapons (Ammunition)"

#define ITEM_CAT_TOOLS_COOKWARE "Tools (Cookware)"
#define ITEM_CAT_TOOLS_FIELD "Tools (Field & Mining)"
#define ITEM_CAT_TOOLS_WORKSHOP "Tools (Smithing & Workshop)"
#define ITEM_CAT_TOOLS_SUNDRIES "Tools (Lights & Sundries)"

#define ITEM_CAT_VALUABLES_RINGS "Valuables (Rings)"
#define ITEM_CAT_VALUABLES_HOLY "Valuables (Holy & Amulets)"

#define ITEM_CAT_DECORATION "Decoration"

#define ITEM_CAT_COMPONENTS "Components"
#define ITEM_CAT_SMITHING_MISC "Smithing (Misc)"

#define ITEM_CAT_ENG_MACHINERY "Engineering (Machinery)"
#define ITEM_CAT_ENG_CONSTRUCTION "Engineering (Construction)"
#define ITEM_CAT_ENG_COMBAT "Engineering (Combat)"
#define ITEM_CAT_ENG_TRIGGERS "Engineering (Triggers & Control)"
#define ITEM_CAT_ENG_MISC "Engineering (Misc)"
