#define RUMOR_POINTS_START 16
#define RUMOR_POINTS_BASE_REFILL 8
#define RUMOR_POINTS_PER_PLAYER 0.04
#define RUMOR_POINTS_CLAWBACK_MULTIPLIER 2

#define GUILD_REFERRAL_FEE_PCT 0.05
#define RUMOR_CONTACT_FEE_PCT 0.25

#define RUMOR_THREAT_GATE_MIN 0.20

GLOBAL_LIST_INIT(rumor_threat_gated_types, list(
	QUEST_KILL_EASY,
	QUEST_CLEAR_OUT,
	QUEST_RAID,
	QUEST_BOUNTY,
	QUEST_RETRIEVAL,
	QUEST_RECOVERY,
))

GLOBAL_LIST_INIT(rumor_point_costs, list(
	QUEST_RETRIEVAL = 2,
	QUEST_COURIER = 2,
	QUEST_KILL_EASY = 2,
	QUEST_CLEAR_OUT = 4,
	QUEST_RECOVERY = 4,
	QUEST_RAID = 6,
	QUEST_BOUNTY = 6,
))
