// Trade good IDs + canonical sellprice defines. One source of truth so trade_goods datums,
// /obj/item sellprices, economic_region produces/demands, standing_orders, and event templates
// all reference the same strings and numbers.

// ---- IDs ----
#define TRADE_GOOD_IRON_ORE "IRON_ORE"
#define TRADE_GOOD_COPPER_ORE "COPPER_ORE"
#define TRADE_GOOD_TIN_ORE "TIN_ORE"
#define TRADE_GOOD_COAL "COAL"
#define TRADE_GOOD_STONE "STONE"
#define TRADE_GOOD_CINNABAR "CINNABAR"
#define TRADE_GOOD_SALT "SALT"
#define TRADE_GOOD_GLASS_BATCH "GLASS_BATCH"

#define TRADE_GOOD_GOLD_ORE "GOLD_ORE"
#define TRADE_GOOD_SILVER_ORE "SILVER_ORE"

#define TRADE_GOOD_IRON_INGOT "IRON_INGOT"
#define TRADE_GOOD_COPPER_INGOT "COPPER_INGOT"
#define TRADE_GOOD_TIN_INGOT "TIN_INGOT"
#define TRADE_GOOD_STEEL_INGOT "STEEL_INGOT"
#define TRADE_GOOD_GOLD_INGOT "GOLD_INGOT"
#define TRADE_GOOD_SILVER_INGOT "SILVER_INGOT"

#define TRADE_GOOD_TOPER "TOPER"
#define TRADE_GOOD_GEMERALD "GEMERALD"
#define TRADE_GOOD_SAFFIRA "SAFFIRA"
#define TRADE_GOOD_BLORTZ "BLORTZ"
#define TRADE_GOOD_DORPEL "DORPEL"
#define TRADE_GOOD_BLOOD_DIAMOND "BLOOD_DIAMOND"

#define TRADE_GOOD_WOOD "WOOD"
#define TRADE_GOOD_DENDOR_ESSENCE "DENDOR_ESSENCE"
#define TRADE_GOOD_VISCERA "VISCERA"

#define TRADE_GOOD_FIBERS "FIBERS"
#define TRADE_GOOD_CLOTH "CLOTH"
#define TRADE_GOOD_SILK "SILK"
#define TRADE_GOOD_HIDE "HIDE"
#define TRADE_GOOD_FUR "FUR"
#define TRADE_GOOD_CURED_LEATHER "CURED_LEATHER"

#define TRADE_GOOD_GRAIN "GRAIN"
#define TRADE_GOOD_OATS "OATS"
#define TRADE_GOOD_RICE "RICE"

#define TRADE_GOOD_MEAT "MEAT"
#define TRADE_GOOD_PORK "PORK"
#define TRADE_GOOD_POULTRY "POULTRY"
#define TRADE_GOOD_RABBIT "RABBIT"
#define TRADE_GOOD_EGG "EGG"
#define TRADE_GOOD_BUTTER "BUTTER"
#define TRADE_GOOD_CHEESE "CHEESE"
#define TRADE_GOOD_FAT "FAT"
#define TRADE_GOOD_TALLOW "TALLOW"

#define TRADE_GOOD_APPLE "APPLE"
#define TRADE_GOOD_PEAR "PEAR"
#define TRADE_GOOD_JACKSBERRY "JACKSBERRY"

#define TRADE_GOOD_CALENDULA "CALENDULA"
#define TRADE_GOOD_POPPY "POPPY"
#define TRADE_GOOD_CABBAGE "CABBAGE"
#define TRADE_GOOD_POTATO "POTATO"
#define TRADE_GOOD_ONION "ONION"
#define TRADE_GOOD_CARROT "CARROT"
#define TRADE_GOOD_TURNIP "TURNIP"

#define TRADE_GOOD_FISH_FILET "FISH_FILET"
#define TRADE_GOOD_FISH_MINCE "FISH_MINCE"
#define TRADE_GOOD_SALMON "SALMON"
#define TRADE_GOOD_COD "COD"
#define TRADE_GOOD_CRAB "CRAB"
#define TRADE_GOOD_BASS "BASS"
#define TRADE_GOOD_CARP "CARP"
#define TRADE_GOOD_SOLE "SOLE"
#define TRADE_GOOD_CLAM "CLAM"
#define TRADE_GOOD_LOBSTER "LOBSTER"
#define TRADE_GOOD_SHRIMP "SHRIMP"

// ---- Sellprices ----
// Minerals
#define SELLPRICE_IRON_ORE 8
#define SELLPRICE_COPPER_ORE 6
#define SELLPRICE_TIN_ORE 7
#define SELLPRICE_COAL 4
#define SELLPRICE_STONE 1
#define SELLPRICE_CINNABAR 5
#define SELLPRICE_SALT 4
#define SELLPRICE_GLASS_BATCH 4

// Precious ores
#define SELLPRICE_GOLD_ORE 50
#define SELLPRICE_SILVER_ORE 80

// Intermediaries - priced just above their ore so smelting-to-stockpile is unprofitable for
// purchased ore but still worthwhile for looted/scavenged ore (e.g. bog iron from mob drops).
#define SELLPRICE_IRON_INGOT 10
#define SELLPRICE_COPPER_INGOT 7
#define SELLPRICE_TIN_INGOT 8
#define SELLPRICE_STEEL_INGOT 14
#define SELLPRICE_GOLD_INGOT 60
#define SELLPRICE_SILVER_INGOT 80

// Gems
#define SELLPRICE_TOPER 34
#define SELLPRICE_GEMERALD 42
#define SELLPRICE_SAFFIRA 56
#define SELLPRICE_BLORTZ 88
#define SELLPRICE_DORPEL 121
#define SELLPRICE_BLOOD_DIAMOND 188

// Artisan raws
#define SELLPRICE_WOOD 3
#define SELLPRICE_DENDOR_ESSENCE 20
#define SELLPRICE_VISCERA 3

// Textile / animal products
#define SELLPRICE_FIBERS 1
#define SELLPRICE_CLOTH 3
#define SELLPRICE_SILK 2
#define SELLPRICE_HIDE 8
#define SELLPRICE_FUR 10
#define SELLPRICE_CURED_LEATHER 3

// Grains
#define SELLPRICE_GRAIN 2
#define SELLPRICE_OATS 2
#define SELLPRICE_RICE 2

// Animal foods
#define SELLPRICE_MEAT 4
#define SELLPRICE_PORK 4
#define SELLPRICE_POULTRY 4
#define SELLPRICE_RABBIT 3
#define SELLPRICE_EGG 2
#define SELLPRICE_BUTTER 9
#define SELLPRICE_CHEESE 3
#define SELLPRICE_FAT 3
#define SELLPRICE_TALLOW 1

// Fruits
#define SELLPRICE_APPLE 2
#define SELLPRICE_PEAR 2
#define SELLPRICE_JACKSBERRY 2

// Vegetables
#define SELLPRICE_CALENDULA 4
#define SELLPRICE_POPPY 2
#define SELLPRICE_CABBAGE 2
#define SELLPRICE_POTATO 2
#define SELLPRICE_ONION 2
#define SELLPRICE_CARROT 2
#define SELLPRICE_TURNIP 2

// Seafood
#define SELLPRICE_FISH_FILET 3
#define SELLPRICE_FISH_MINCE 2
#define SELLPRICE_SALMON 4
#define SELLPRICE_COD 4
#define SELLPRICE_CRAB 4
#define SELLPRICE_BASS 4
#define SELLPRICE_CARP 4
#define SELLPRICE_SOLE 4
#define SELLPRICE_CLAM 4
#define SELLPRICE_LOBSTER 4
#define SELLPRICE_SHRIMP 4
