// Trade good IDs + canonical sellprice defines. One source of truth so trade_goods datums,
// /obj/item sellprices, economic_region produces/demands, standing_orders, and event templates
// all reference the same strings and numbers.

// ---- IDs ----
#define TRADE_GOOD_IRON_ORE "IRON_ORE"
#define TRADE_GOOD_COPPER_ORE "COPPER_ORE"
#define TRADE_GOOD_TIN_ORE "TIN_ORE"
#define TRADE_GOOD_COAL "COAL"
#define TRADE_GOOD_STONE "STONE"
#define TRADE_GOOD_CINNABAR "CINNABAR"
#define TRADE_GOOD_SALT "SALT"
#define TRADE_GOOD_GLASS_BATCH "GLASS_BATCH"

#define TRADE_GOOD_GOLD_ORE "GOLD_ORE"
#define TRADE_GOOD_SILVER_ORE "SILVER_ORE"

#define TRADE_GOOD_IRON_INGOT "IRON_INGOT"
#define TRADE_GOOD_COPPER_INGOT "COPPER_INGOT"
#define TRADE_GOOD_TIN_INGOT "TIN_INGOT"
#define TRADE_GOOD_STEEL_INGOT "STEEL_INGOT"
#define TRADE_GOOD_GOLD_INGOT "GOLD_INGOT"
#define TRADE_GOOD_SILVER_INGOT "SILVER_INGOT"

#define TRADE_GOOD_TOPER "TOPER"
#define TRADE_GOOD_GEMERALD "GEMERALD"
#define TRADE_GOOD_SAFFIRA "SAFFIRA"
#define TRADE_GOOD_BLORTZ "BLORTZ"
#define TRADE_GOOD_DORPEL "DORPEL"
#define TRADE_GOOD_BLOOD_DIAMOND "BLOOD_DIAMOND"

#define TRADE_GOOD_WOOD "WOOD"
#define TRADE_GOOD_DENDOR_ESSENCE "DENDOR_ESSENCE"
#define TRADE_GOOD_VISCERA "VISCERA"

#define TRADE_GOOD_FIBERS "FIBERS"
#define TRADE_GOOD_CLOTH "CLOTH"
#define TRADE_GOOD_SILK "SILK"
#define TRADE_GOOD_HIDE "HIDE"
#define TRADE_GOOD_FUR "FUR"
#define TRADE_GOOD_CURED_LEATHER "CURED_LEATHER"

#define TRADE_GOOD_GRAIN "GRAIN"
#define TRADE_GOOD_OATS "OATS"
#define TRADE_GOOD_RICE "RICE"

#define TRADE_GOOD_MEAT "MEAT"
#define TRADE_GOOD_PORK "PORK"
#define TRADE_GOOD_POULTRY "POULTRY"
#define TRADE_GOOD_RABBIT "RABBIT"
#define TRADE_GOOD_EGG "EGG"
#define TRADE_GOOD_BUTTER "BUTTER"
#define TRADE_GOOD_CHEESE "CHEESE"
#define TRADE_GOOD_FAT "FAT"
#define TRADE_GOOD_TALLOW "TALLOW"

#define TRADE_GOOD_APPLE "APPLE"
#define TRADE_GOOD_PEAR "PEAR"
#define TRADE_GOOD_JACKSBERRY "JACKSBERRY"

#define TRADE_GOOD_CALENDULA "CALENDULA"
#define TRADE_GOOD_POPPY "POPPY"
#define TRADE_GOOD_CABBAGE "CABBAGE"
#define TRADE_GOOD_POTATO "POTATO"
#define TRADE_GOOD_ONION "ONION"
#define TRADE_GOOD_CARROT "CARROT"
#define TRADE_GOOD_TURNIP "TURNIP"

#define TRADE_GOOD_FISH_FILET "FISH_FILET"
#define TRADE_GOOD_FISH_MINCE "FISH_MINCE"
#define TRADE_GOOD_SALMON "SALMON"
#define TRADE_GOOD_COD "COD"
#define TRADE_GOOD_CRAB "CRAB"
#define TRADE_GOOD_BASS "BASS"
#define TRADE_GOOD_CARP "CARP"
#define TRADE_GOOD_SOLE "SOLE"
#define TRADE_GOOD_CLAM "CLAM"
#define TRADE_GOOD_LOBSTER "LOBSTER"
#define TRADE_GOOD_SHRIMP "SHRIMP"

// Equipment (finished goods, fulfilled via warehouse, never stockpiled)
#define TRADE_GOOD_STEEL_ARMING_SWORD "STEEL_ARMING_SWORD"
#define TRADE_GOOD_STEEL_SHORTSWORD "STEEL_SHORTSWORD"
#define TRADE_GOOD_STEEL_FALCHION "STEEL_FALCHION"
#define TRADE_GOOD_STEEL_MESSER "STEEL_MESSER"
#define TRADE_GOOD_STEEL_SABRE "STEEL_SABRE"
#define TRADE_GOOD_STEEL_MACE "STEEL_MACE"
#define TRADE_GOOD_STEEL_FLANGED_MACE "STEEL_FLANGED_MACE"
#define TRADE_GOOD_STEEL_FLAIL "STEEL_FLAIL"
#define TRADE_GOOD_STEEL_LONGSWORD "STEEL_LONGSWORD"
#define TRADE_GOOD_STEEL_BROADSWORD "STEEL_BROADSWORD"
#define TRADE_GOOD_STEEL_WARHAMMER "STEEL_WARHAMMER"
#define TRADE_GOOD_STEEL_BATTLEAXE "STEEL_BATTLEAXE"
#define TRADE_GOOD_HURLBAT "HURLBAT"
#define TRADE_GOOD_STEEL_GREATSWORD "STEEL_GREATSWORD"
#define TRADE_GOOD_STEEL_HALBERD "STEEL_HALBERD"
#define TRADE_GOOD_STEEL_EAGLEBEAK "STEEL_EAGLEBEAK"
#define TRADE_GOOD_RECURVE_BOW "RECURVE_BOW"
#define TRADE_GOOD_PADDED_GAMBESON "PADDED_GAMBESON"
#define TRADE_GOOD_HEAVY_LEATHER_COAT "HEAVY_LEATHER_COAT"
#define TRADE_GOOD_STEEL_CHAINMAIL "STEEL_CHAINMAIL"
#define TRADE_GOOD_STEEL_HAUBERK "STEEL_HAUBERK"
#define TRADE_GOOD_BRIGANDINE "BRIGANDINE"
#define TRADE_GOOD_BRIGANDINE_HEAVY "BRIGANDINE_HEAVY"
#define TRADE_GOOD_STEEL_CUIRASS "STEEL_CUIRASS"
#define TRADE_GOOD_STEEL_COATPLATES "STEEL_COATPLATES"
#define TRADE_GOOD_STEEL_HALFPLATE "STEEL_HALFPLATE"
#define TRADE_GOOD_STEEL_FULLPLATE "STEEL_FULLPLATE"
#define TRADE_GOOD_STEEL_HELM_KNIGHT "STEEL_HELM_KNIGHT"
#define TRADE_GOOD_STEEL_HELM_BASCINET "STEEL_HELM_BASCINET"
#define TRADE_GOOD_STEEL_HELM_KETTLE "STEEL_HELM_KETTLE"
#define TRADE_GOOD_STEEL_MASK "STEEL_MASK"
#define TRADE_GOOD_CHAIN_GLOVES "CHAIN_GLOVES"
#define TRADE_GOOD_PLATE_GAUNTLETS "PLATE_GAUNTLETS"
#define TRADE_GOOD_STEEL_PLATE_LEGS "STEEL_PLATE_LEGS"

// ---- Sellprices ----
// Minerals
#define SELLPRICE_IRON_ORE 8
#define SELLPRICE_COPPER_ORE 6
#define SELLPRICE_TIN_ORE 7
#define SELLPRICE_COAL 4
#define SELLPRICE_STONE 2
#define SELLPRICE_CINNABAR 5
#define SELLPRICE_SALT 4
#define SELLPRICE_GLASS_BATCH 4

// Precious ores
#define SELLPRICE_GOLD_ORE 50
#define SELLPRICE_SILVER_ORE 80

// Intermediaries - priced just above their ore so smelting-to-stockpile is unprofitable for
// purchased ore but still worthwhile for looted/scavenged ore (e.g. bog iron from mob drops).
#define SELLPRICE_IRON_INGOT 10
#define SELLPRICE_COPPER_INGOT 7
#define SELLPRICE_TIN_INGOT 8
#define SELLPRICE_STEEL_INGOT 14
#define SELLPRICE_GOLD_INGOT 60
#define SELLPRICE_SILVER_INGOT 80

// Gems
#define SELLPRICE_TOPER 34
#define SELLPRICE_GEMERALD 42
#define SELLPRICE_SAFFIRA 56
#define SELLPRICE_BLORTZ 88
#define SELLPRICE_DORPEL 121
#define SELLPRICE_BLOOD_DIAMOND 188

// Artisan raws
#define SELLPRICE_WOOD 3
#define SELLPRICE_DENDOR_ESSENCE 20
#define SELLPRICE_VISCERA 3

// Textile / animal products
#define SELLPRICE_FIBERS 2
#define SELLPRICE_CLOTH 3
#define SELLPRICE_SILK 2
#define SELLPRICE_HIDE 8
#define SELLPRICE_FUR 10
#define SELLPRICE_CURED_LEATHER 3

// Grains
#define SELLPRICE_GRAIN 3
#define SELLPRICE_OATS 3
#define SELLPRICE_RICE 3

// Animal foods
#define SELLPRICE_MEAT 4
#define SELLPRICE_PORK 4
#define SELLPRICE_POULTRY 4
#define SELLPRICE_RABBIT 3
#define SELLPRICE_EGG 2
#define SELLPRICE_BUTTER 9
#define SELLPRICE_CHEESE 3
#define SELLPRICE_FAT 3
#define SELLPRICE_TALLOW 2

// Fruits
#define SELLPRICE_APPLE 3
#define SELLPRICE_PEAR 3
#define SELLPRICE_JACKSBERRY 3

// Vegetables
#define SELLPRICE_CALENDULA 4
#define SELLPRICE_POPPY 3
#define SELLPRICE_CABBAGE 3
#define SELLPRICE_POTATO 3
#define SELLPRICE_ONION 3
#define SELLPRICE_CARROT 3
#define SELLPRICE_TURNIP 3

// Seafood
#define SELLPRICE_FISH_FILET 3
#define SELLPRICE_FISH_MINCE 2
#define SELLPRICE_SALMON 4
#define SELLPRICE_COD 4
#define SELLPRICE_CRAB 4
#define SELLPRICE_BASS 4
#define SELLPRICE_CARP 4
#define SELLPRICE_SOLE 4
#define SELLPRICE_CLAM 4
#define SELLPRICE_LOBSTER 4
#define SELLPRICE_SHRIMP 4
