#define REALM_AAVNR "aavnr"
#define REALM_GRENZELHOFT "grenzelhoft"
#define REALM_OTAVA "otava"
#define REALM_KAZENGUN "kazengun"
#define REALM_HAMMERHOLD "hammerhold"
#define REALM_ETRUSCA "etrusca"
#define REALM_GRONN "gronn"
#define REALM_LIRVAS "lirvas"
#define REALM_LINGYUE "lingyue"
#define REALM_NALEDI "naledi"
#define REALM_RANESHEN "raneshen"

#define TRADE_SHIP_DOCK_DURATION (60 MINUTES)
#define TRADE_SHIP_SEND_AWAY_GRACE (20 MINUTES)

#define TRADE_SHIPS_PER_DAY_ROLL 8
#define TRADE_SHIPS_HAIL_PER_DAY 2

#define TRADE_SHIP_DOCK_SPOTS_BASE 2
#define TRADE_SHIP_DOCK_SPOTS_MAX 4

#define TRADE_SHIP_EXPECTED_FAVOR 500
/*
	Massive fractional nerf for supply and only supply so that merchant cannot end
	shortages easily on their own or completely replace production roles.
*/
#define TRADE_SHIP_SUPPLY_QTY_FRACTION 0.15
#define TRADE_SHIP_DEFAULT_TONNAGE 100
#define TRADE_SHIP_TONNAGE_VARIANCE 0.3
#define TRADE_SHIP_TONNAGE_SCALE_CAP 2.0
#define TRADE_SHIP_TONNAGE_SCALE_SPAN 700

#define FAVOR_PASSIVE_TRADE_FRACTION 0.5

#define TRADE_REALM_WEIGHT_DEFAULT 10
#define TRADE_REALM_WEIGHT_NEIGHBOR 20
#define TRADE_REALM_WEIGHT_DISTANT 10
#define TRADE_REALM_WEIGHT_RARE 5

#define TRADE_SHIP_BULK_LINES_MIN 1
#define TRADE_SHIP_BULK_LINES_MAX 3

#define BULK_QTY_TINY_MIN 2
#define BULK_QTY_TINY_MAX 5
#define BULK_QTY_SMALL_MIN 10
#define BULK_QTY_SMALL_MAX 20
#define BULK_QTY_MEDIUM_MIN 15
#define BULK_QTY_MEDIUM_MAX 35
#define BULK_QTY_LARGE_MIN 20
#define BULK_QTY_LARGE_MAX 50
#define BULK_QTY_HUGE_MIN 25
#define BULK_QTY_HUGE_MAX 55

#define BULK_PRICE_DEEP_DISCOUNT 0.6
#define BULK_PRICE_DISCOUNT 0.7
#define BULK_PRICE_FAIR 0.85
#define BULK_PRICE_PREMIUM 1.2
#define BULK_PRICE_EAGER_PREMIUM 1.35
#define BULK_PRICE_DESPERATE 1.5

#define TRADE_MERCHANT_MIDDLEMAN_CUT_PERCENT 25
#define TRADE_MERCHANT_LEVY_DEFAULT_PERCENT 25
#define TRADE_MERCHANT_LEVY_CAP_PERCENT 50
#define TRADE_CULTURAL_SHIP_DISCOUNT_PERCENT 50

// For any upgrades you can buy
#define ADDITIONAL_PIER_FAVOR 1250
#define GNOME_AUTOMATION_FAVOR 2500

#define FAVOR_SEND_CLEAN_THRESHOLD 1.0
#define FAVOR_SEND_PARTIAL_THRESHOLD 0.5
#define FAVOR_SEND_CLEAN_MULT 1.0
#define FAVOR_SEND_PARTIAL_MULT 0.5
#define FAVOR_SEND_FAILURE_PENALTY 250

#define FAVOR_OUTCOME_HONORED "honored"
#define FAVOR_OUTCOME_PARTIAL "partial"
#define FAVOR_OUTCOME_DISHONORED "dishonored"

// Triumph bonus brackets - high water mark, not subtractable by spend
#define FAVOR_TRIUMPH_BRACKET_1 500
#define FAVOR_TRIUMPH_BRACKET_2 1000
#define FAVOR_TRIUMPH_BRACKET_3 1750
#define FAVOR_TRIUMPH_BRACKET_4 2500
#define FAVOR_TRIUMPH_BRACKET_5 3500
#define FAVOR_TRIUMPH_BRACKET_6 5000
#define FAVOR_TRIUMPH_BONUS_CAP 6

#define TRADE_SHIP_STATE_AVAILABLE "available"
#define TRADE_SHIP_STATE_DOCKED "docked"

#define TRADE_VICTUALLING_FRESH_LINES_MIN 2
#define TRADE_VICTUALLING_FRESH_LINES_MAX 4
#define TRADE_VICTUALLING_PRESERVED_LINES_MIN 1
#define TRADE_VICTUALLING_PRESERVED_LINES_MAX 2
#define TRADE_VICTUALLING_ALCOHOL_LINES_MIN 2
#define TRADE_VICTUALLING_ALCOHOL_LINES_MAX 4
#define TRADE_VICTUALLING_QTY_PER_LINE_MIN 3
#define TRADE_VICTUALLING_QTY_PER_LINE_MAX 6
#define TRADE_VICTUALLING_PRICE_MOD 1.2
#define TRADE_ALCOHOL_EXPORT_MARKUP 1.4
#define TRADE_VICTUALLING_TAG_FRESH "victualling_fresh"
#define TRADE_VICTUALLING_TAG_PRESERVED "victualling_preserved"
#define TRADE_VICTUALLING_TAG_ALCOHOL "victualling_alcohol"

#define CONDITION_OP_MODIFY "modify"
#define CONDITION_OP_REMOVE "remove"
#define CONDITION_OP_ADD "add"
#define CONDITION_OP_MODIFY_CULTURAL "modify_cultural"

#define CONDITION_PRICE_HEAVY 1.6
#define CONDITION_PRICE_MODERATE 1.3
#define CONDITION_PRICE_LIGHT 1.15
#define CONDITION_PRICE_CHEAP 0.85
#define CONDITION_PRICE_VERY_CHEAP 0.7

#define CONDITION_QTY_HEAVY 1.6
#define CONDITION_QTY_MODERATE 1.3
#define CONDITION_QTY_LIGHT 1.15
#define CONDITION_QTY_LOW 0.7
#define CONDITION_QTY_VERY_LOW 0.4
