/proc/get_market_pool_tier_for_category(category)
	switch(category)
		if(ITEM_CAT_VALUABLES_RINGS, ITEM_CAT_VALUABLES_HOLY, ITEM_CAT_DECORATION, ITEM_CAT_TROPHY)
			return MARKET_POOL_TIER_LOOT
		if(ITEM_CAT_FOODSTUFF_FRESH, ITEM_CAT_FOODSTUFF_PRESERVED, ITEM_CAT_BEVERAGE, ITEM_CAT_GARMENT_LUXURY)
			return MARKET_POOL_TIER_MID
	return MARKET_POOL_TIER_STANDARD

/proc/all_market_pool_categories()
	return list(
		ITEM_CAT_ARMOR_HELMETS, ITEM_CAT_ARMOR_CHESTPIECES, ITEM_CAT_ARMOR_LEGS,
		ITEM_CAT_ARMOR_NECK, ITEM_CAT_ARMOR_BOOTS, ITEM_CAT_ARMOR_GLOVES,
		ITEM_CAT_ARMOR_MASKS, ITEM_CAT_ARMOR_BRACERS, ITEM_CAT_ARMOR_BELTS,
		ITEM_CAT_ARMOR_BARDING, ITEM_CAT_ARMOR_LIGHT,
		ITEM_CAT_WEAPONS_SWORDS, ITEM_CAT_WEAPONS_DAGGERS, ITEM_CAT_WEAPONS_AXES,
		ITEM_CAT_WEAPONS_POLEARMS, ITEM_CAT_WEAPONS_MACES, ITEM_CAT_WEAPONS_FLAILS,
		ITEM_CAT_WEAPONS_SHIELDS, ITEM_CAT_WEAPONS_AMMO,
		ITEM_CAT_TOOLS_COOKWARE, ITEM_CAT_TOOLS_FIELD, ITEM_CAT_TOOLS_WORKSHOP,
		ITEM_CAT_TOOLS_SUNDRIES, ITEM_CAT_TOOLS_ROGUE,
		ITEM_CAT_VALUABLES_RINGS, ITEM_CAT_VALUABLES_HOLY,
		ITEM_CAT_DECORATION, ITEM_CAT_POTTERY, ITEM_CAT_COMPONENTS, ITEM_CAT_SMITHING_MISC,
		ITEM_CAT_ENG_MACHINERY, ITEM_CAT_ENG_CONSTRUCTION, ITEM_CAT_ENG_COMBAT,
		ITEM_CAT_ENG_TRIGGERS, ITEM_CAT_ENG_MISC,
		ITEM_CAT_GARMENT_COMMON, ITEM_CAT_GARMENT_FINE, ITEM_CAT_GARMENT_LUXURY,
		ITEM_CAT_FOODSTUFF_FRESH, ITEM_CAT_FOODSTUFF_PRESERVED,
		ITEM_CAT_POTION, ITEM_CAT_BEVERAGE,
		ITEM_CAT_BOOK_WRIT, ITEM_CAT_INSTRUMENT,
		ITEM_CAT_TROPHY, ITEM_CAT_SALVAGE, ITEM_CAT_LIVESTOCK,
		ITEM_CAT_RAW_MATERIAL_MINERAL, ITEM_CAT_RAW_MATERIAL_ORGANIC,
		ITEM_CAT_REAGENT_ALCHEMICAL, ITEM_CAT_REAGENT_ARCANE, ITEM_CAT_ARCYNE_GEARS,
	)

/proc/compute_market_pool_capacity(category, pop_count)
	var/baseline = get_market_pool_tier_for_category(category)
	var/pop_mult = 1 + MARKET_POOL_POP_SCALE * max(0, pop_count - MARKET_POOL_POP_REFERENCE)
	var/jitter = MARKET_POOL_JITTER_LOW + rand() * (MARKET_POOL_JITTER_HIGH - MARKET_POOL_JITTER_LOW)
	return round(baseline * pop_mult * jitter)

/proc/compute_pop_count_for_pools()
	return length(GLOB.clients)
