#define ZAD_FLIGHT_TRAVEL_HEIGHT 256
#define ZAD_ASCEND_DURATION (8 SECONDS)
#define ZAD_DESCEND_DURATION (8 SECONDS)
#define ZAD_BOMB_DESCEND_DURATION_VAR_MIN (13 SECONDS)
#define ZAD_BOMB_DESCEND_DURATION_VAR_MAX (18 SECONDS)
